services:
    _defaults:
        public: true

    App\Service\Planner\PlannerInterface:
        alias: 'App\Service\Planner\BasicPlanner'
    
    App\Service\AssignmentGenerator:
        arguments:
            $combinationGenerator: '@App\Service\Math\CombinationGenerator'
