services:
    _defaults:
        public: true
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'
            - '../src/Backtracking/'


    App\Service\Planner\BasicPlanner:
        shared: false
        arguments:
            $planner: '@App\Service\Planner\BacktrackingPlanner'
            $validator: '@validator'
    
    App\Service\Planner\BacktrackingPlanner:
        shared: false